### ISSUE TITLE
Where do I obtain cleancss?

### ISSUE THREAD

**Issue by swift2plunder** [appsattic/imagelicious.org#1]
https://github.com/appsattic/imagelicious.org/commit/91ac73e92dd911112c86c7c24702943fc596ccf9

This commit added CSS minification into production, but I do not have the "cleancss" tool installed and the build fails without it. I'm going to hack around this with cp for testing purposes, but I would like to see a link to the tool required added to the README

Tx!

**Comment by chilts** [comment]
Ah yes, sorry. You'll have to do a `npm install` in the top level directory to install cleancss, and lots and lots of other stuff related to babel and React. :)

I should add a 'Contributing' section to the ReadMe.md :)

**Comment by chilts** [comment]
Thanks for raising this issue. :)

**Comment by swift2plunder** [comment]
In 4.0, clean-css broke the command line utility into a separate package. In order to install the cleancss command with 4.0+, you need clean-css-cli. Simply adding the new package to the devDependencies section of package.json didn't seem to resolve the issue for me otherwise I would've prepared a pull request for you. I needed to install the new package with the -g switch.
